import React, { forwardRef } from 'react';
import { cn } from '@/lib/utils';

interface PrintableDocumentProps {
  children: React.ReactNode;
  className?: string;
  title?: string;
  showBranding?: boolean;
}

/**
 * PrintableDocument - A wrapper component that provides print-friendly styling
 * 
 * Use this wrapper around any content that should be printable via browser print.
 * The component applies LAVANDAR branding and proper print CSS rules.
 * 
 * Note: Uses print-specific inline styles since Tailwind classes may not apply in print context
 */
export const PrintableDocument = forwardRef<HTMLDivElement, PrintableDocumentProps>(
  ({ children, className, title, showBranding = true }, ref) => {
    return (
      <div
        ref={ref}
        className={cn('print-document', className)}
        style={{ backgroundColor: 'white', color: '#18181b' }}
      >
        {showBranding && (
          <div className="print-header hidden print:block">
            <div style={{ height: '4px', backgroundColor: '#7c3aed', width: '100%' }} />
            <div 
              className="flex justify-between items-center px-8 py-4"
              style={{ borderBottom: '1px solid #e4e4e7' }}
            >
              <span 
                className="text-sm font-bold tracking-wider"
                style={{ color: '#7c3aed' }}
              >
                LAVANDAR
              </span>
              {title && (
                <span 
                  className="text-lg font-medium"
                  style={{ color: '#18181b' }}
                >
                  {title}
                </span>
              )}
              <span className="text-xs" style={{ color: '#71717a' }}>
                {new Date().toLocaleString('en-US', {
                  year: 'numeric',
                  month: '2-digit',
                  day: '2-digit',
                  hour: '2-digit',
                  minute: '2-digit',
                  timeZoneName: 'short',
                })}
              </span>
            </div>
          </div>
        )}

        <div className="print-content">
          {children}
        </div>

        {showBranding && (
          <div className="print-footer hidden print:block fixed bottom-0 left-0 right-0">
            <div 
              className="text-center py-4"
              style={{ borderTop: '1px solid #e4e4e7' }}
            >
              <p className="text-xs italic" style={{ color: '#71717a' }}>
                Generated by LAVANDAR Intelligence Platform
              </p>
            </div>
          </div>
        )}
      </div>
    );
  }
);

PrintableDocument.displayName = 'PrintableDocument';

/**
 * PrintSection - A semantic section within a printable document
 */
export function PrintSection({
  children,
  title,
  className,
}: {
  children: React.ReactNode;
  title?: string;
  className?: string;
}) {
  return (
    <section className={cn('print-section mb-6', className)}>
      {title && (
        <h2 
          className="text-sm font-bold uppercase tracking-wider mb-3 pb-2"
          style={{ color: '#3f3f46', borderBottom: '1px solid #e4e4e7' }}
        >
          {title}
        </h2>
      )}
      {children}
    </section>
  );
}

/**
 * PrintTable - A styled table optimized for print
 */
export function PrintTable({
  headers,
  rows,
  className,
}: {
  headers: string[];
  rows: (string | number | React.ReactNode)[][];
  className?: string;
}) {
  return (
    <table className={cn('w-full text-sm', className)} style={{ borderCollapse: 'collapse' }}>
      <thead>
        <tr style={{ backgroundColor: '#7c3aed', color: 'white' }}>
          {headers.map((header, i) => (
            <th
              key={i}
              className="px-3 py-2 text-left text-xs font-bold uppercase tracking-wider"
            >
              {header}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, rowIndex) => (
          <tr
            key={rowIndex}
            style={{ backgroundColor: rowIndex % 2 === 0 ? 'white' : '#faf5ff' }}
          >
            {row.map((cell, cellIndex) => (
              <td 
                key={cellIndex} 
                className="px-3 py-2"
                style={{ borderBottom: '1px solid #e4e4e7' }}
              >
                {cell}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

/**
 * PrintInfoBox - A highlighted info box for key details
 */
export function PrintInfoBox({
  items,
  columns = 2,
  className,
}: {
  items: { label: string; value: string }[];
  columns?: 2 | 3;
  className?: string;
}) {
  return (
    <div
      className={cn(
        'rounded-lg p-4 mb-4 grid gap-3',
        columns === 2 ? 'grid-cols-2' : 'grid-cols-3',
        className
      )}
      style={{ backgroundColor: '#ede9fe' }}
    >
      {items.map((item, i) => (
        <div key={i} className="flex gap-2">
          <span 
            className="text-xs font-bold uppercase"
            style={{ color: '#71717a' }}
          >
            {item.label}:
          </span>
          <span className="text-xs" style={{ color: '#18181b' }}>
            {item.value}
          </span>
        </div>
      ))}
    </div>
  );
}
