import { useCallback } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

// LAVANDAR brand colors (RGB tuples for jsPDF)
const LAVENDER_600: [number, number, number] = [124, 58, 237]; // #7c3aed
const LAVENDER_100: [number, number, number] = [237, 233, 254]; // #ede9fe
const ZINC_900: [number, number, number] = [24, 24, 27]; // #18181b
const ZINC_500: [number, number, number] = [113, 113, 122]; // #71717a
const ZINC_300: [number, number, number] = [212, 212, 216]; // #d4d4d8
const WHITE: [number, number, number] = [255, 255, 255];
const ALT_ROW: [number, number, number] = [250, 250, 255];

export interface PrintConfig {
  documentTitle: string;
  filename?: string;
  orientation?: 'portrait' | 'landscape';
  showHeader?: boolean;
  showFooter?: boolean;
  showTimestamp?: boolean;
}

export interface TableData {
  head: string[][];
  body: (string | number)[][];
  columnStyles?: Record<number, { cellWidth?: number | 'auto' }>;
}

export function usePrintExport() {
  /**
   * Creates a new jsPDF document with LAVANDAR branding
   */
  const createDocument = useCallback((config: PrintConfig): jsPDF => {
    const doc = new jsPDF({
      orientation: config.orientation || 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    return doc;
  }, []);

  /**
   * Adds the LAVANDAR branded header to the document
   */
  const addHeader = useCallback((doc: jsPDF, title: string, subtitle?: string) => {
    const pageWidth = doc.internal.pageSize.getWidth();
    let yPos = 15;

    // Lavender accent bar
    doc.setFillColor(LAVENDER_600[0], LAVENDER_600[1], LAVENDER_600[2]);
    doc.rect(0, 0, pageWidth, 3, 'F');

    // LAVANDAR wordmark
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(LAVENDER_600[0], LAVENDER_600[1], LAVENDER_600[2]);
    doc.text('LAVANDAR', 14, yPos);

    // Timestamp in JST format
    const timestamp = format(new Date(), "yyyy-MM-dd HH:mm 'JST'");
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(ZINC_500[0], ZINC_500[1], ZINC_500[2]);
    doc.text(timestamp, pageWidth - 14, yPos, { align: 'right' });

    yPos += 12;

    // Document title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(ZINC_900[0], ZINC_900[1], ZINC_900[2]);
    doc.text(title, 14, yPos);

    if (subtitle) {
      yPos += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(ZINC_500[0], ZINC_500[1], ZINC_500[2]);
      doc.text(subtitle, 14, yPos);
    }

    yPos += 10;

    // Separator line
    doc.setDrawColor(ZINC_300[0], ZINC_300[1], ZINC_300[2]);
    doc.setLineWidth(0.2);
    doc.line(14, yPos, pageWidth - 14, yPos);

    return yPos + 8;
  }, []);

  /**
   * Adds the consistent footer to all pages
   */
  const addFooter = useCallback((doc: jsPDF) => {
    const pageCount = doc.getNumberOfPages();
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.getWidth();

    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      
      // Footer separator
      doc.setDrawColor(ZINC_300[0], ZINC_300[1], ZINC_300[2]);
      doc.setLineWidth(0.2);
      doc.line(14, pageHeight - 18, pageWidth - 14, pageHeight - 18);

      // Footer text
      doc.setFontSize(7);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(ZINC_500[0], ZINC_500[1], ZINC_500[2]);
      doc.text(
        'Generated by LAVANDAR Intelligence Platform',
        pageWidth / 2,
        pageHeight - 12,
        { align: 'center' }
      );

      // Page number
      doc.setFont('helvetica', 'normal');
      doc.text(
        `Page ${i} of ${pageCount}`,
        pageWidth - 14,
        pageHeight - 12,
        { align: 'right' }
      );
    }
  }, []);

  /**
   * Adds a branded info box section
   */
  const addInfoBox = useCallback((
    doc: jsPDF,
    yPos: number,
    data: { label: string; value: string }[],
    columns: 2 | 3 = 2
  ) => {
    const pageWidth = doc.internal.pageSize.getWidth();
    const boxWidth = pageWidth - 28;
    const boxHeight = Math.ceil(data.length / columns) * 12 + 8;

    // Background box
    doc.setFillColor(LAVENDER_100[0], LAVENDER_100[1], LAVENDER_100[2]);
    doc.roundedRect(14, yPos, boxWidth, boxHeight, 2, 2, 'F');

    const colWidth = boxWidth / columns;

    data.forEach((item, index) => {
      const col = index % columns;
      const row = Math.floor(index / columns);
      const xPos = 20 + col * colWidth;
      const itemY = yPos + 8 + row * 12;

      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(ZINC_500[0], ZINC_500[1], ZINC_500[2]);
      doc.text(item.label, xPos, itemY);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(ZINC_900[0], ZINC_900[1], ZINC_900[2]);
      doc.text(item.value, xPos + 35, itemY);
    });

    return yPos + boxHeight + 8;
  }, []);

  /**
   * Adds a styled table using jspdf-autotable
   */
  const addTable = useCallback((
    doc: jsPDF,
    yPos: number,
    tableData: TableData
  ): number => {
    autoTable(doc, {
      startY: yPos,
      head: tableData.head,
      body: tableData.body,
      theme: 'striped',
      headStyles: {
        fillColor: LAVENDER_600,
        fontSize: 9,
        fontStyle: 'bold',
        textColor: WHITE,
      },
      bodyStyles: {
        fontSize: 8,
        textColor: ZINC_900,
      },
      alternateRowStyles: {
        fillColor: ALT_ROW,
      },
      columnStyles: tableData.columnStyles || {},
      margin: { left: 14, right: 14 },
    });

    return (doc as any).lastAutoTable.finalY + 10;
  }, []);

  /**
   * Adds a section title
   */
  const addSectionTitle = useCallback((doc: jsPDF, yPos: number, title: string) => {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(ZINC_900[0], ZINC_900[1], ZINC_900[2]);
    doc.text(title, 14, yPos);

    return yPos + 6;
  }, []);

  /**
   * Checks if page break is needed and adds new page if necessary
   */
  const checkPageBreak = useCallback((doc: jsPDF, yPos: number, requiredSpace: number = 40): number => {
    const pageHeight = doc.internal.pageSize.getHeight();
    
    if (yPos + requiredSpace > pageHeight - 25) {
      doc.addPage();
      return 20;
    }
    
    return yPos;
  }, []);

  /**
   * Saves the document with generated filename
   */
  const saveDocument = useCallback((doc: jsPDF, config: PrintConfig) => {
    const timestamp = format(new Date(), 'yyyy-MM-dd');
    const filename = config.filename || 
      `${config.documentTitle.toLowerCase().replace(/\s+/g, '-')}-${timestamp}.pdf`;
    
    doc.save(filename);
  }, []);

  /**
   * Triggers browser print dialog
   */
  const browserPrint = useCallback(() => {
    window.print();
  }, []);

  return {
    createDocument,
    addHeader,
    addFooter,
    addInfoBox,
    addTable,
    addSectionTitle,
    checkPageBreak,
    saveDocument,
    browserPrint,
    // Brand colors for custom usage
    colors: {
      LAVENDER_600,
      LAVENDER_100,
      ZINC_900,
      ZINC_500,
      ZINC_300,
    },
  };
}

export type UsePrintExportReturn = ReturnType<typeof usePrintExport>;
